name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build & Deploy to GitHub Pages
      env: 
        MARP_ARGS: "index.md -o index.html"
        # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # GITHUB_REPOSITORY: ${{ github.repository }}
        PUBLISH_TO_BRANCH: gh-pages
        BASE_URL: https://uprootx.github.io/cat-show/
        MARP_USER: root:root
      uses: ralexander-phi/marp-action@master
      